name: "CI and Build Tests"

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  Setup-Environment:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requirements
        run: >
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  Linux-Build:
      needs: Setup-Environment
      runs-on: ubuntu-latest
      permissions:
        pages: write
        id-token: write
      steps:
        - name: Linux Build
          run: |
            pyinstaller --onefile --windowed --add-data="UI/Themes/*.qss:UI/Themes" --add-data="Backend/Books_Database/BooksDatabase.db:Backend/Books_Database" --name=BookFinder main.py
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: linux-exe
            path: dist/BookFinder
